In [73]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [74]:
df=pd.read_csv('creditcard.csv')

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [96]:
df['Class'].unique()

array([0, 1], dtype=int64)

In [97]:
df.describe()1


SyntaxError: invalid syntax (<ipython-input-97-5b667212f764>, line 1)

In [98]:
from sklearn.ensemble import RandomForestClassifier

In [99]:
rfc=RandomForestClassifier(n_estimators=10)

In [103]:
from sklearn.model_selection import train_test_split
X=df.drop(['Class'],axis=1)
y=df['Class']

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [105]:
rfc.fit(X_train,y_train)

KeyboardInterrupt: 

In [36]:
pred=rfc.predict(X_test)

In [37]:
from sklearn.metrics import classification_report

In [38]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     93838
           1       0.92      0.73      0.82       149

    accuracy                           1.00     93987
   macro avg       0.96      0.87      0.91     93987
weighted avg       1.00      1.00      1.00     93987



In [18]:
df.shape

(284807, 31)

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Dense,Dropout

In [ ]:
mod1=Sequential()

In [106]:
mod1.add(Dense(30,activation='relu'))
mod1.add(Dropout(0.2))
mod1.add(Dense(20,activation='relu'))
mod1.add(Dropout(0.2))
mod1.add(Dense(10,activation='relu'))
mod1.add(Dropout(0.2))
mod1.add(Dense(5,activation='relu'))
mod1.add(Dropout(0.2))
mod1.add(Dense(5,activation='relu'))
mod1.add(Dropout(0.2))
mod1.add(Dense(1,activation='sigmoid'))
mod1.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

In [107]:
from sklearn.preprocessing import StandardScaler


In [108]:
scaler=StandardScaler()

In [109]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


In [111]:
mod1.fit(x=X_train,y=y_train,validation_data=(X_test,y_test),epochs=10,batch_size=128)

Train on 190820 samples, validate on 93987 samples
Epoch 1/10
190820/190820 [==============================] - 9s 45us/sample - loss: 0.0142 - accuracy: 0.9982 - val_loss: 0.0119 - val_accuracy: 0.9984
Epoch 2/10
190820/190820 [==============================] - 8s 42us/sample - loss: 0.0140 - accuracy: 0.9982 - val_loss: 0.0118 - val_accuracy: 0.9984
Epoch 3/10
190820/190820 [==============================] - 9s 45us/sample - loss: 0.0139 - accuracy: 0.9982 - val_loss: 0.0118 - val_accuracy: 0.9984
Epoch 4/10
190820/190820 [==============================] - 8s 42us/sample - loss: 0.0138 - accuracy: 0.9982 - val_loss: 0.0118 - val_accuracy: 0.9984
Epoch 5/10
190820/190820 [==============================] - 9s 45us/sample - loss: 0.0137 - accuracy: 0.9982 - val_loss: 0.0118 - val_accuracy: 0.9984
Epoch 6/10
190820/190820 [==============================] - 8s 42us/sample - loss: 0.0137 - accuracy: 0.9982 - val_loss: 0.0118 - val_accuracy: 0.9984
Epoch 7/10
190820/190820 [=================

In [115]:
from sklearn.metrics import classification_report

In [116]:
pred=model.predict(X_test)

In [118]:
pred

array([[0.        , 6.393692  ],
       [0.        , 1.0382825 ],
       [0.15082721, 0.252569  ],
       ...,
       [0.        , 0.33503962],
       [0.        , 0.        ],
       [0.        , 0.44765761]], dtype=float32)

In [119]:
True_values=y_test

In [121]:
True_values.shape

(93987,)

In [122]:
pred.shape

(93987, 2)

In [123]:
pred

array([[0.        , 6.393692  ],
       [0.        , 1.0382825 ],
       [0.15082721, 0.252569  ],
       ...,
       [0.        , 0.33503962],
       [0.        , 0.        ],
       [0.        , 0.44765761]], dtype=float32)